### ISSUE TITLE
Decrypt

### ISSUE THREAD

**Issue by nicolak** [halilhanbadem/AES-256-CBCEncryptionDelphi_PHP#1]
How to decrypt (Delphi)?

**Comment by halilhanbadem** [comment]
"IPWorks! Encrypt" for Delphi for this.
Trial: https://www.nsoftware.com/ipworks/encrypt/download.aspx
Demo: https://yazilimtoplulugu.com/aesencdemo.zip 

> The DCPCrpyt component had such support, but I used it instead of dealing with it.

**Comment by halilhanbadem** [comment]
The purpose of this project was to make secure payments. Therefore, the encrypted data from the Delphi application was sent to the PHP file and the payment was made successfully.

If binary communication is involved, you can use the component mentioned above. AES is an encryption type that requires much detail. You need to do it carefully when adjusting.

**Comment by nicolak** [comment]
Thanks.
